import fs from 'fs';

const lines = [
  `'use client';`,
  ``,
  `import { useState } from 'react';`,
  `import { useRouter } from 'next/navigation';`,
  `import { createClient } from '@/utils/supabase/client';`,
  ``,
  `export default function LoginPage() {`,
  `  const [username, setUsername] = useState('');`,
  `  const [password, setPassword] = useState('');`,
  `  const [isSignUp, setIsSignUp] = useState(false);`,
  `  const [loading, setLoading] = useState(false);`,
  `  const [error, setError] = useState('');`,
  `  const router = useRouter();`,
  ``,
  `  const handleSubmit = async (e: React.FormEvent) => {`,
  `    e.preventDefault();`,
  `    setLoading(true);`,
  `    setError('');`,
  ``,
  `    try {`,
  `      const supabase = createClient();`,
  ``,
  `      if (isSignUp) {`,
  `        const { data, error: signUpError } = await supabase.auth.signUp({`,
  `          email: username + '@charlies-star-road.local',`,
  `          password,`,
  `          options: { data: { username } },`,
  `        });`,
  `        if (signUpError) throw signUpError;`,
  `        if (data.user) {`,
  `          await supabase.from('profiles').insert({ id: data.user.id, username });`,
  `        }`,
  `        setError('\u6ce8\u518c\u6210\u529f\uff01\u8bf7\u767b\u5f55');`,
  `        setIsSignUp(false);`,
  `      } else {`,
  `        const { error: signInError } = await supabase.auth.signInWithPassword({`,
  `          email: username + '@charlies-star-road.local',`,
  `          password,`,
  `        });`,
  `        if (signInError) throw signInError;`,
  `        router.push('/game');`,
  `        router.refresh();`,
  `      }`,
  `    } catch (err: unknown) {`,
  `      const message = err instanceof Error ? err.message : '\u672a\u77e5\u9519\u8bef';`,
  `      setError(message);`,
  `    } finally {`,
  `      setLoading(false);`,
  `    }`,
  `  };`,
  ``,
  `  return (`,
  `    <div className="min-h-screen flex items-center justify-center bg-gradient-to-b from-indigo-950 via-purple-900 to-slate-950 p-4">`,
  `      <div className="w-full max-w-md">`,
  `        <div className="text-center mb-8">`,
  `          <h1 className="text-4xl font-bold bg-gradient-to-r from-yellow-300 via-pink-400 to-cyan-400 bg-clip-text text-transparent">`,
  `            Charlie's Star Road`,
  `          </h1>`,
  `          <p className="text-purple-200/70 mt-2 text-sm">\u8ddf\u5468\u6df1\u4e00\u8d77\u73af\u6e38\u4e16\u754c\u5b66\u82f1\u8bed</p>`,
  `        </div>`,
  `        <div className="bg-white/10 backdrop-blur-xl rounded-3xl p-8 border border-white/20 shadow-2xl">`,
  `          <form onSubmit={handleSubmit} className="space-y-5">`,
  `            <div>`,
  `              <label className="block text-sm font-medium text-purple-200 mb-1.5">\u7528\u6237\u540d</label>`,
  `              <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} required minLength={3} placeholder="\u8f93\u5165\u4f60\u7684\u7528\u6237\u540d" className="w-full px-4 py-3 rounded-xl bg-white/10 border border-white/20 text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-yellow-400/50 focus:border-transparent transition-all" />`,
  `            </div>`,
  `            <div>`,
  `              <label className="block text-sm font-medium text-purple-200 mb-1.5">\u5bc6\u7801</label>`,
  `              <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={6} placeholder="\u81f3\u5c111\u4f4d\u5bc6\u7801" className="w-full px-4 py-3 rounded-xl bg-white/10 border border-white/20 text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-yellow-400/50 focus:border-transparent transition-all" />`,
  `            </div>`,
  `            {error && (`,
  `              <div className={'p-3 rounded-xl text-sm ' + (isSignUp ? 'bg-green-500/20 text-green-300' : 'bg-red-500/20 text-red-300')}>{error}</div>`,
  `            )}`,
  `            <button type="submit" disabled={loading} className="w-full py-3 rounded-xl font-semibold text-lg bg-gradient-to-r from-yellow-400 to-orange-500 text-indigo-950 hover:from-yellow-300 hover:to-orange-400 disabled:opacity-50 transition-all transform hover:scale-[1.02] active:scale-[0.98]">`,
  `              {loading ? '\u5904\u7406\u4e2d...' : isSignUp ? '\u6ce8\u518c\u8d26\u53f7' : '\u5f00\u59cb\u65c5\u7a0b'}`,
  `            </button>`,
  `          </form>`,
  `          <p className="text-center mt-6 text-sm text-purple-200/60">`,
  `            {isSignUp ? '\u5df2\u6709\u8d26\u53f7\uff1f' : '\u8fd8\u6ca1\u6709\u8d26\u53f7\uff1f'}`,
  `            {' '}`,
  `            <button onClick={() => { setIsSignUp(!isSignUp); setError(''); }} className="text-yellow-400 hover:text-yellow-300 font-medium underline underline-offset-2">{isSignUp ? '\u53bb\u767b\u5f55' : '\u7acb\u5373\u6ce8\u518c'}</button>`,
  `          </p>`,
  `        </div>`,
  `        <p className="text-center mt-6 text-xs text-purple-200/30">Powered by Supabase Auth</p>`,
  `      </div>`,
  `    </div>`,
  `  );`,
  `}`,
];

const outPath = "D:/Develope/Charlie's-Star-Road/app/login/page.tsx";
fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log('OK:' + outPath);
